### ISSUE TITLE
iOS Third Party Keyboards 

### ISSUE THREAD

**Issue by JanBakker88** [MicrosoftDocs/IntuneDocs.nl-nl#101]
"The Intune app protection policy (APP) support for the Third Party Keyboards setting for iOS is no longer supported due to an iOS platform change. You will not be able to configure this setting in the Intune Admin Console and it will not be enforced on the client in the Intune App SDK."

Still visible on this page tho.... ;) 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: bf2c5494-686e-8aa3-2be2-77594ecd59b5
* Version Independent ID: 614dc53a-caa6-56cc-3a8d-564f392b4f46
* Content: [Instellingen voor beveiligingsbeleid voor iOS-apps](https://docs.microsoft.com/nl-nl/intune/app-protection-policy-settings-ios)
* Content Source: [intune/app-protection-policy-settings-ios.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/app-protection-policy-settings-ios.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by CeciAc** [comment]
Hello, @JanBakker88

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/2357

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
