### ISSUE TITLE
Please update the dynamic device rules to reflect new dynamic rule options for Azure AD groups

### ISSUE THREAD

**Issue by kennethvs** [MicrosoftDocs/IntuneDocs.nl-nl#102]
(device.devicePhysicalIDs -any _ -contains "[ZTDId]") should become (device.devicePhysicalIDs -any (_ -contains "[ZTDId]")) for example

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 72a05275-8b82-1832-f8b8-7df18b2cc100
* Version Independent ID: d752da20-e306-e218-b654-6b0d7147473d
* Content: [Apparaten inschrijven met Windows Autopilot - Microsoft Intune](https://docs.microsoft.com/nl-nl/intune/enrollment-autopilot#feedback)
* Content Source: [intune/enrollment-autopilot.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/enrollment-autopilot.md)
* Service: **microsoft-intune**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by srvbpigh** [comment]
Hello, @kennethvs
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kennethvs

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/2943

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
