### ISSUE TITLE
Link does not work

### ISSUE THREAD

**Issue by parlevjo2** [MicrosoftDocs/IntuneDocs.nl-nl#104]
If I go tho link "Microsoft Intune administration console" in this article: https://manage.microsoft.com/ I get not supported browser message. I tried Chrome, Opera. Both the same

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: ea056a36-19c7-a60a-bdf6-fc038100ad7e
* Version Independent ID: 597c14aa-7d9a-2fa6-ac5e-8d7161a7fdc4
* Content: [Hardware- en software-inventaris voor Windows-computers weergeven - Microsoft Intune](https://docs.microsoft.com/nl-nl/intune/fundamentals/view-hardware-and-software-inventory-for-windows-pcs-in-microsoft-intune#feedback)
* Content Source: [intune/fundamentals/view-hardware-and-software-inventory-for-windows-pcs-in-microsoft-intune.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/fundamentals/view-hardware-and-software-inventory-for-windows-pcs-in-microsoft-intune.md)
* Service: **microsoft-intune**
* Sub-service: **fundamentals**
* Technology: ****
* GitHub Login: @dougeby
* Microsoft Alias: **dougeby**

**Comment by srvbpigh** [comment]
Hello, @parlevjo2
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @parlevjo2 
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?

I cannot reproduce the error, it leads me to a login page.

Kind regards,
Microsoft DOCS International Team

**Comment by parlevjo2** [comment]
If you login, you will get: https://admin.manage.microsoft.com/MicrosoftIntune/Error.aspx?E=5
Also if you are already logged inthrough portal.office.com and you goto https://manage.microsoft.com/ I I get https://admin.manage.microsoft.com/MicrosoftIntune/Error.aspx?E=5

**Comment by CeciAc** [comment]
Hello, @parlevjo2 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/3266

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
