### ISSUE TITLE
Rotate the FileVault Key macOS

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/IntuneDocs.nl-nl#106]
Any technical documentation on how this works? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 5b7c5dea-ab57-b08a-bfeb-02e30a0dab61
* Version Independent ID: a1c460b4-a591-695d-951c-9a9b4b49afc5
* Content: [Apparaten versleutelen met de versleutelingsmethode die wordt ondersteund op platforms - Microsoft Intune](https://docs.microsoft.com/nl-nl/intune/protect/encrypt-devices)
* Content Source: [intune/protect/encrypt-devices.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/protect/encrypt-devices.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by srvbpigh** [comment]
Hello, @BakkerJan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @BakkerJan

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here -https://github.com/MicrosoftDocs/IntuneDocs/issues/3314

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
