### ISSUE TITLE
Microsoft Intune management extension does not install on WVD

### ISSUE THREAD

**Issue by rviersel** [MicrosoftDocs/IntuneDocs.nl-nl#107]
Microsoft Intune management extension MSI does not install on Windows Virtual Desktop (yet?)
This needs might need to be mentioned here.

/Application/MsiInstaller/EventID:10005:"Product: Microsoft Intune Management Extension -- This application only runs on Windows 10 or higher"

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 82e3024b-28df-c8c8-da24-6cc30c52ef05
* Version Independent ID: 6a5ee3c7-4c52-c2b1-0b1d-e4ba6ebf6f9b
* Content: [PowerShell-scripts aan Windows 10-apparaten toevoegen in Microsoft Intune - Azure](https://docs.microsoft.com/nl-nl/intune/apps/intune-management-extension#feedback)
* Content Source: [intune/apps/intune-management-extension.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/apps/intune-management-extension.md)
* Service: **microsoft-intune**
* Sub-service: **apps**
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by srvbpigh** [comment]
Hello, @rviersel
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @rviersel, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/3432. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
