### ISSUE TITLE
Clarify IMEI

### ISSUE THREAD

**Issue by BakkerJan** [MicrosoftDocs/IntuneDocs.nl-nl#108]
The table states that IMEI is not supported for iOS and Android. But the introduction states that it works. Can you clarify this? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: eee9d3bf-e496-2227-5855-dd64f2c7b851
* Version Independent ID: a4f02105-c202-9961-c259-d4fc9ed8b910
* Content: [Zakelijke id’s toevoegen aan Intune](https://docs.microsoft.com/nl-nl/intune/enrollment/corporate-identifiers-add)
* Content Source: [intune/enrollment/corporate-identifiers-add.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/enrollment/corporate-identifiers-add.md)
* Service: **microsoft-intune**
* Sub-service: **enrollment**
* Technology: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by srvbpigh** [comment]
Hello, @BakkerJan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @BakkerJan, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/IntuneDocs/issues/3496. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @BakkerJan

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @BakkerJan,

Thank you for your linguistic feedback.  

Unfortunately, after reviewing your feedback our linguistic team considered it to be not fully aligned with our criteria for acceptance because the source text states that all platforms with IMEI numbers are supported and that serial numbers are supported for iOS and Android devices. It does not say that IMEI numbers are supported for iOS and Android. The translation states exactly the same. Thus the translation is also correct. The comment by the contributor has been checked and the translation is correct. No further action is needed.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.  

Kind regards, 

Microsoft DOCS International Team
